class XDispatch: ...


class XDispatchProvider: ...


class XStatusListener:
    def disposing(self, _event) -> None: ...
    def statusChanged(self, state) -> None: ...


class XToolbarController:
    def execute(self, key_modifier: int) -> None: ...
    def click(self) -> None: ...
    def doubleClick(self) -> None: ...
    def createPopupWindow(self): ...
    def createItemWindow(self, parent): ...


class XTerminateListener:
    def disposing(self, _event) -> None: ...
    def queryTermination(self, _event) -> None: ...
    def notifyTermination(self, _event) -> None: ...
