class XDispatch: ...


class XDispatchProvider: ...


class XTerminateListener:
    def disposing(self, _event) -> None: ...
    def queryTermination(self, _event) -> None: ...
    def notifyTermination(self, _event) -> None: ...
