class Base: ...


class ImplementationHelper:
    def addImplementation(self, factory, implementation_name: str, service_names) -> None: ...
    def writeRegistryInfo(self, registry_key, service_manager) -> int: ...
