class XActionListener:
    def disposing(self, _event) -> None: ...
    def actionPerformed(self, action_event) -> None: ...


class XItemListener:
    def disposing(self, _event) -> None: ...
    def itemStateChanged(self, item_event) -> None: ...


class XTextListener:
    def disposing(self, _event) -> None: ...
    def textChanged(self, text_event) -> None: ...
