"""UNO AWT listener interfaces used by the native extension dialogs."""

class XActionListener:
    def disposing(self, _event) -> None: ...
    def actionPerformed(self, action_event) -> None: ...

class XItemListener:
    def disposing(self, _event) -> None: ...
    def itemStateChanged(self, item_event) -> None: ...

class XCallback:
    def notify(self, data) -> None: ...
