# SPDX-FileCopyrightText: 2026 Bora Yarkin
# SPDX-License-Identifier: GPL-3.0-only

from __future__ import annotations

import base64
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.shared_webui import (  # noqa: E402
    build_localization_manifest_text,
    build_webui_manifest_text,
    iter_webui_files,
    trusted_index_html,
)

SOURCE = ROOT / "deploy" / "cloudflare" / "src" / "index.mjs"
OUTPUT = ROOT / "deploy" / "cloudflare" / "dashboard-worker.mjs"


def _content_type(path: str) -> str:
    if path.endswith(".html"):
        return "text/html; charset=utf-8"
    if path.endswith(".css"):
        return "text/css; charset=utf-8"
    if path.endswith(".js") or path.endswith(".mjs"):
        return "application/javascript; charset=utf-8"
    if path.endswith(".json"):
        return "application/json; charset=utf-8"
    return "application/octet-stream"


def _asset_payload() -> dict[str, dict[str, str]]:
    assets: dict[str, dict[str, str]] = {}
    for source, relative_path in iter_webui_files():
        relative_name = str(relative_path).replace("\\", "/")
        data = (
            trusted_index_html().encode("utf-8")
            if relative_name == "index.html"
            else source.read_bytes()
        )
        assets[f"/{relative_name}"] = {
            "contentType": _content_type(relative_name),
            "data": base64.b64encode(data).decode("ascii"),
        }

    for relative_name, text in (
        ("localizations/manifest.json", build_localization_manifest_text()),
        ("asset-manifest.json", build_webui_manifest_text()),
    ):
        assets[f"/{relative_name}"] = {
            "contentType": _content_type(relative_name),
            "data": base64.b64encode(text.encode("utf-8")).decode("ascii"),
        }
    return assets


def build_dashboard_worker_text() -> str:
    source = SOURCE.read_text(encoding="utf-8")
    source = source.replace(
        "    return env.ASSETS.fetch(request)\n",
        "    return serveEmbeddedAsset(request)\n",
    )
    if "env.ASSETS.fetch" in source:
        raise RuntimeError("Cloudflare source still depends on the ASSETS binding")

    assets_json = json.dumps(_asset_payload(), indent=2, sort_keys=True)
    return (
        "// Generated by tools/build_cloudflare_dashboard_worker.py. Do not edit.\n"
        "// Paste this file into Cloudflare Workers for browser-only relay deployment.\n"
        f"{source.rstrip()}\n\n"
        f"const EMBEDDED_ASSETS = {assets_json}\n\n"
        "function serveEmbeddedAsset(request){\n"
        "  const url = new URL(request.url)\n"
        "  const path = url.pathname === '/' ? '/index.html' : url.pathname\n"
        "  const asset = EMBEDDED_ASSETS[path]\n"
        "  if(!asset){\n"
        "    return new Response('relay.error.notFound', {status: 404})\n"
        "  }\n"
        "  return new Response(base64ToBytes(asset.data), {\n"
        "    headers: {\n"
        "      'Content-Type': asset.contentType,\n"
        "      'Cache-Control': 'no-store',\n"
        "      'X-Content-Type-Options': 'nosniff',\n"
        "      'Referrer-Policy': 'no-referrer',\n"
        "      'X-Frame-Options': 'DENY',\n"
        "    },\n"
        "  })\n"
        "}\n\n"
        "function base64ToBytes(value){\n"
        "  const decoded = atob(value)\n"
        "  const bytes = new Uint8Array(decoded.length)\n"
        "  for(let index = 0; index < decoded.length; index += 1){\n"
        "    bytes[index] = decoded.charCodeAt(index)\n"
        "  }\n"
        "  return bytes\n"
        "}\n"
    )


def main() -> None:
    OUTPUT.write_text(build_dashboard_worker_text(), encoding="utf-8")
    print(OUTPUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
